{ pkgs,
  pkgs-unstable,
  system,
  inputs,
 ...}:
let
  themes = pkgs.callPackage  ./configs/sddm-themes.nix {};
  packages = [ 
    inputs.tmux-booster
  ];
  unstable = with pkgs-unstable; [
    ferdium
    spotify
    lazygit
    lazydocker
    nodePackages."@antfu/ni"
    nodejs_20
    mongodb-compass
    mongosh
    mongodb-tools
    darktable
    obsidian
    librewolf
    fastfetch
    ranger
    ueberzugpp
  ];
  stable = with pkgs; [
  #  vim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
  #  wget
    wlr-randr
    neovim
    tmux
    git
    openssh
    hyprland 
    hyprpaper
    waybar
    waypaper
    firefox-wayland 
    alacritty 
    rofi-wayland
    keyd
    gnome.nautilus
    eog
    xwayland
    xdg-desktop-portal-hyprland
    xdg-desktop-portal-gtk
    nix-prefetch-git
    libsForQt5.qt5.qtquickcontrols2
    libsForQt5.qt5.qtgraphicaleffects
    fzf
    ripgrep
    wl-clipboard
    killall
    pulseaudio
    hyprlock
    pavucontrol
    wev # xevents to see keyboard and mouse events
    brightnessctl
    eza
    networkmanagerapplet
    btop
    slurp
    grim
    cinnamon.nemo-with-extensions   
    vlc
    mpv
    kitty
    lf
    gwenview
    gcc
    node2nix
    nixd
    docker
    kubectl
    kubeseal
    doctl
    transmission
    transmission-gtk
    python3
    playerctl
    inkscape
    themes.where-is-my-sddm-theme
    lua-language-server
    xz
    exfat
    gnome.gnome-disk-utility
    docker-compose
    unzip
    jq
    weston
    lm_sensors
    gimp
    baobab
    zoxide
  ];
in
{
  environment.systemPackages = stable ++ unstable ++ packages;
}
