gui:
  showIcons: true
  showFileTree: false
  theme:
    optionsTextColor:
      - '#3b4261'
    selectedLineBgColor:
      - '#3b4261' # set to `default` to have no background colour
    activeBorderColor:
      - blue
    inactiveBorderColor:
      - '#3b4261'

git:
  merging:
    args: "--no-ff"
  pull:
    mode: "ff-only" # one of 'merge' | 'rebase' | 'ff-only'
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)' --all"
